config/routes.rb
Rails.application.routes.draw do
  if Rails.env.development?
    mount GraphiQL::Rails::Engine, at: "/graphiql", graphql_path: "/graphql"
  end
  post "/graphql", to: "graphql#execute"
get '/stocks', to:'stocks#index'
get '/contacts', to: 'contacts#index' 

resources :contacts
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/contact.rb
class Contact < ApplicationRecord
    validates :Name, presence:true
    validates :Email, presence:true
    validates :Content, presence:true
    validates :Content, length:{in:1..140}

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  def index
    @contacts = Contact.all
  end

  def new
    @contact = Contact.new
  end

  def show
    @contact = Contact.find(params[:id])
  end

  def edit
    @contact = Contact.find(params[:id])
  end

  def destroy
    @contact = Contact.find(params[:id])
    @contact.destroy
    redirect_to contacts_path, notice: "削除しました！"
  end

  def update
    @contact = Contact.find(params[:id])
    if @contact.update(contact_params)
      redirect_to contacts_path, notice: "内容変更しました！"
      else
        render :edit

    end
  end

  def create
    #Contact.create(Name: params[:contact][:Name],Email: params[:contact][:Email],Content: params[:contact][:content])
    #Contact.create(params.require(:contact).permit(:Name, :Email, :Content))
    @contact = Contact.new(Name: params[:contact][:Name],Email: params[:contact][:Email],Content: params[:contact][:content])
    if @contact.save
      redirect_to new_contact_path, notice: "作成しました！"
    else
      render :new
    end
  end
  private

  def contact_params
    params.require(:contact).permit(:Name, :Email, :Content)
  end
end

app/controllers/graphql_controller.rb
class GraphqlController < ApplicationController
  # If accessing from outside this domain, nullify the session
  # This allows for outside API access while preventing CSRF attacks,
  # but you'll have to authenticate your user separately
  # protect_from_forgery with: :null_session

  def execute
    variables = prepare_variables(params[:variables])
    query = params[:query]
    operation_name = params[:operationName]
    context = {
      # Query context goes here, for example:
      # current_user: current_user,
      contact: Contact.last
    }
    result = ExercisesSchema.execute(query, variables: variables, context: context, operation_name: operation_name)
    render json: result
  rescue StandardError => e
    raise e unless Rails.env.development?
    handle_error_in_development(e)
  end

  private

  # Handle variables in form data, JSON body, or a blank value
  def prepare_variables(variables_param)
    case variables_param
    when String
      if variables_param.present?
        JSON.parse(variables_param) || {}
      else
        {}
      end
    when Hash
      variables_param
    when ActionController::Parameters
      variables_param.to_unsafe_hash # GraphQL-Ruby will validate name and type of incoming variables.
    when nil
      {}
    else
      raise ArgumentError, "Unexpected parameter: #{variables_param}"
    end
  end

  def handle_error_in_development(e)
    logger.error e.message
    logger.error e.backtrace.join("\n")

    render json: { errors: [{ message: e.message, backtrace: e.backtrace }], data: {} }, status: 500
  end
end

app/controllers/stocks_controller.rb
class StocksController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/stocks_helper.rb
module StocksHelper
end

app/views/contacts/edit.html.erb
<%= form_with(model: @contact, local: true) do |form|%>    
    <% if @contact.errors.any? %>
  <div id="error_explanation">
    <h2><%= @contact.errors.count %>件のエラーがあります。</h2>
    <ul>
    <% @contact.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>


    <div class="contact_Name">
     <%= form.label :Name%>
     <br><%= form.text_field :Name%>
    </div>
    
    <div class="contact_Email">
     <%= form.label :Email %>
     <br><%= form.text_field :Email%>
    </div>

    <div class="contact_Content">
     <%= form.label :Content %>
     <br><%= form.text_field :Content%>
    </div>
    <%= form.submit %>

<% end %>

<%= link_to 'コンタクト一覧画面へ', contacts_path%>

app/views/contacts/index.html.erb
<h1>コンタクト一覧</h1>

<table>
    <tr>
      <th>名前</th>
      <th>メールアドレス</th>
      <th>内容</th>
    </tr>

<% @contacts.each do |contact| %>
    <tr>
      <td><%= contact.Name %></td>
      <td><%= contact.Email%></td>
      <td><%= contact.Content%></td>
      <td><%= link_to '詳細確認する', contact_path(contact.id) %></td>
      <td><%= link_to '内容を変更する', edit_contact_path(contact.id),data: { confirm: '本当に編集していいですか？' }%></td>
      <td><%= link_to '内容を削除する', contact_path(contact.id), method: :delete ,data: { confirm: '本当に削除していいですか？' }  %>
    </tr>
<% end %>
</table>

<%= link_to '新規入力画面に戻る',new_contact_path %>

app/views/contacts/new.html.erb
<%= form_with(model: @contact, local: true) do |form|%>    
    <% if @contact.errors.any? %>
  <div id="error_explanation">
    <h2><%= @contact.errors.count %>件のエラーがあります。</h2>
    <ul>
    <% @contact.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>


    <div class="contact_Name">
     <%= form.label :Name%>
     <br><%= form.text_field :Name%>
    </div>
    
    <div class="contact_Email">
     <%= form.label :Email %>
     <br><%= form.text_field :Email%>
    </div>

    <div class="contact_Content">
     <%= form.label :content %>
     <br><%= form.text_field :content%>
    </div>
    <%= form.submit %>

<% end %>

<%= link_to 'コンタクト一覧画面へ', contacts_path%>

app/views/contacts/show.html.erb
<h1>コンタクト詳細画面</h1>
<p>名前:<br><%= @contact.Name %></p>
<p>メールアドレス:<br><%= @contact.Email %></p>
<p>内容:<br><%= @contact.Content %></p>

<%= link_to 'コンタクト一覧画面へ', contacts_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Exercises</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/stocks/index.html.erb
<h1>Stocks#index</h1>
<p>Find me in app/views/stocks/index.html.erb</p>